# Base configuration
compatibility_date = "2024-01-01"
main = "cloudflare/functions/nearby-places.js"
name = "nearby-places-worker"

[observability.logs]
enabled = true

# KV namespace configuration
[[kv_namespaces]]
binding = "PLACES_KV"
id = "0ef6fb2b2e93475a8e3c41db695f9136"
preview_id = "7fb49c091ac54ac99051205d00398e26"

# Environment configurations
[env.production]
vars = { ENVIRONMENT = "production" }

# Remove routes section since we're using workers.dev domain
# [[routes]]
# pattern = "api/nearby-places"
# zone_name = "barzo.app"

# Use secrets for sensitive values
# Run: wrangler secret put GOOGLE_MAPS_API_KEY