name = "barzo-push"
main = "./worker/index.js"
compatibility_date = "2024-01-28"

[vars]
VAPID_PUBLIC_KEY = "BDvq04Lz9f3hxRmwHc7WP2jNE_r9qbE3_UVbXYdyZKJPC6jVSY9ZnWDsY7Y07Yf2hYbBxNmOHhxvPnB4YBw0Qr8"
VAPID_PRIVATE_KEY = "fGwj0ZXYuMB_tTZ2TwNz8_2bFBGYrTZXxWpZ9rQgQzM"

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
# Replace these with the actual IDs from the commands above
preview_id = "628b86ab4567407d8055fe59cdce66d1"
id = "21c7ec146ba344b8817d6209932a2634" 