name = "nearby-places-worker"
main = "cloudflare/functions/nearby-places.js"
compatibility_date = "2024-01-01"

# Remove routes section since we're using workers.dev domain
# [[routes]]
# pattern = "api/nearby-places"
# zone_name = "barzo.app"

[vars]
# The following will be replaced by actual environment variables
# GOOGLE_MAPS_API_KEY = "your-api-key"

# Use secrets for sensitive values
# Run: wrangler secret put GOOGLE_MAPS_API_KEY